appName: "Timezone Clock"

defaults:
        colors:
                description: white
                time: DeepSkyBlue2
                date: white
                background: black
        frame:
                width: 200
                height: 100
        label:
                font:
                        face: Arial
                        size: 20
                        weight: bold
                padding:
                        x: 20
                        y: 3
                justify: left
        format:
                date: "%Y/%m/%d"
                time: "%H:%M:%S"
        window:
                width: 500
                height: 1

TimeZones:
        America:
                Los_Angeles:
                        description: "Los Angeles"
                        tz: "America/Los_Angeles"
                Indianapolis:
                        description: Indianapolis
                        tz: "America/Indiana/Indianapolis"
                        colors:
                                description: yellow
                                time: yellow
                                date: yellow
                Halifax:
                        description: Halifax
                        tz: "America/Halifax"
        UTC:
                UTC:
                        description: UTC
                        tz: UTC
                        colors:
                                description: "orange red"
                                time: "orange red"
                                date: "orange red"
        Europe:
                Dublin:
                        tz: "Europe/Dublin"
                London:
                        description: "London"
                        tz: "Europe/London"
        Australia:
                Sydney:
                        description: "Sydney"
                        tz: "Australia/Sydney"
